[package]
name = "func"
version = "0.1.0"
edition = "2021"
authors = ["utsho"]

[dependencies]
rustyline = { version = "11.0.0", default-features = false, features = ["with-file-history"] }

[profile.release]
opt-level = 3
strip = true
